name: SonarQube Scan - ASP.NET Framework

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

        - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Begin SonarQube analysis
      run: |
        dotnet-sonarscanner begin /k:"doanchuyennganh" /d:sonar.host.url="http://192.168.183.132:9000" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

    - name: Build the solution
      run: |
        msbuild DoAn_LapTrinhWeb.sln

    - name: End SonarQube analysis
      run: |
        dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
